config/routes.rb
ProcureIo::Application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

  root to: 'home#index', constraints: Clearance::Constraints::SignedOut.new
  root to: 'home#dashboard', constraints: Clearance::Constraints::SignedIn.new, as: :dashboard

  get 'for_vendors' => 'home#for_vendors'

  #### Clearance routes
  resources :passwords,
    :controller => 'clearance/passwords',
    :only => [:create, :new]

  resource :session,
    :controller => 'clearance/sessions',
    :only => [:create, :new, :destroy]

  resources :users,
    :controller => 'users',
    :only => [:create, :new] do
      resource :password,
        :controller => 'clearance/passwords',
        :only => [:create, :edit, :update]

      get 'accept_invite', on: :member
      post 'accept_invite' => 'users#post_accept_invite', on: :member
    end

  namespace :god do
    post 'login_as'
  end

  get '/sign_in' => 'clearance/sessions#new', :as => 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', :as => 'sign_out'
  get '/sign_up' => 'users#new', :as => 'sign_up'
  #### end clearance routes

  get 'settings/profile' => 'settings#profile', as: :settings_profile
  post 'settings/profile' => 'settings#post_profile'
  get 'settings/notifications' => 'settings#notifications', as: :settings_notifications
  post 'settings/notifications' => 'settings#post_notifications'
  get 'settings/account' => 'settings#account', as: :settings_account
  post 'settings/account' => 'settings#post_account'

  resources :notifications, only: [:index, :update]

  resources :saved_searches, only: [:index, :create, :destroy]

  resources :vendors do
    get 'profile', on: :member
    post 'profile' => 'vendors#post_profile', on: :member
    get 'admin', on: :member
    get 'members', on: :member
    post 'member' => 'vendors#add_member', on: :member
    delete 'member' => 'vendors#remove_member', on: :member
    post 'assign_ownership', on: :member
    delete 'leave', on: :member

    resources :bids, controller: :vendor_bids
    resources :registrations, controller: :vendor_registrations
  end

  resources :watches, only: [:create]

  resources :projects do
    get 'created', on: :member
    get 'admin', on: :member
    get 'teams' => 'projects#teams', on: :member
    post 'team' => 'projects#add_team', on: :member
    delete 'team' => 'projects#remove_team', on: :member
    get 'reviewer_leaderboard' => 'projects#reviewer_leaderboard', on: :member
    get 'review_mode' => 'projects#review_mode', on: :member
    post 'review_mode' => 'projects#post_review_mode', on: :member
    get 'comments', on: :member
    get 'import_csv' => 'projects#import_csv', on: :member
    post 'import_csv' => 'projects#post_import_csv', on: :member
    get 'export_csv' => 'projects#export_csv', on: :member
    post 'export_csv' => 'projects#post_export_csv', on: :member
    get 'response_fields' => 'projects#response_fields', on: :member

    resources :reports, only: [] do
      get 'bids_over_time', on: :collection
      get 'impressions', on: :collection
      get 'response_field', on: :collection
    end

    resources :bids do
      post 'edit' => 'bids#post_edit', on: :member
      get 'emails', on: :collection
      put 'batch', on: :collection
      get 'reviews', on: :member
      post 'read_notifications', on: :member
    end

    resources :project_revisions, only: [:show] do
      post 'restore', on: :member
    end

    resources :project_attachments, only: [:destroy]

    resources :amendments
    resources :labels, only: [:create, :destroy, :update]
    resources :questions
  end

  resources :response_fields do
    put 'batch', on: :collection
    delete 'response' => 'response_fields#delete_response', on: :member
  end

  resources :comments

  get '404' => 'errors#not_found'

  resources :organizations, path: '', except: [:index, :new, :create] do
    get 'admin', on: :member
    get 'members', on: :member

    resources :teams do
      get 'members', on: :member
      post 'member' => 'teams#add_member', on: :member
      delete 'member' => 'teams#remove_member', on: :member
    end

    resources :form_templates do
      # post 'create_from_existing', on: :collection
      # get 'pick' => 'form_templates#pick_template', on: :collection
      # get 'preview', on: :member
      # post 'use', on: :member
    end

    resources :projects, controller: :organization_projects
    resources :registrations, controller: :organization_registrations
    resources :vendor_registrations, controller: :organization_vendor_registrations do
      post 'approve', on: :member
      post 'reject', on: :member
    end
  end
end

app/views/shared/_form.html.haml
- if response_fieldable.form_options["form_description"]
  %span.help-block= response_fieldable.form_options["form_description"]

= form_tag form_action, method: (defined?(form_method) ? form_method : :post), id: "responsable-form", class: "responsable-form", :"data-validate" => "parsley", multipart: true do
  %input{"type" => "hidden", "name" => "draft_only"}

  - # We need to display server-side validations for users without js.
  - # Besides, we're already writing the server-side validations for security purposes anyway.
  %noscript
    - if responsable.id && responsable.responsable_errors && !responsable.responsable_errors.empty?
      .alert.alert-danger
        %ul
          - responsable.responsable_errors.each do |e|
            %li= e

  = yield

  = render "shared/form_fields", response_fields: (defined?(response_fields) ? response_fields : response_fieldable.response_fields), responsable: responsable, response_fieldable: response_fieldable

  .form-actions
    %button.btn.btn-primary= defined?(button_text) ? button_text : t('g.submit')
    - if !defined?(save_draft_button) || save_draft_button
      %a.btn#save-draft-button{"data-loading-text" => "All Changes Saved"}= t('g.save_draft')

- if responsable.id && false
  :javascript
    $("#responsable-form").parsley('validate')

app/views/shared/_form_fields.html.haml
- response_fields.each do |response_field|
  .response-field-wrapper.control-group
    = render "shared/fields/#{response_field[:field_type].downcase}", response_field: response_field, |
      value: defined?(responsable) && (r = responsable.responses.where(response_field_id: response_field.id).first) ? r.value : '', |
      response_fieldable: defined?(response_fieldable) ? response_fieldable : nil, responsable: defined?(responsable) ? responsable : nil

app/views/shared/_loading_indicator.html.haml
.loading-indicator
  %i.icon-refresh.icon-spin
  = I18n.t('g.loading')

app/views/shared/_user_sidebar.html.haml
.row-fluid.user-sidebar-row
  .span3
    .user-sidebar
      .accordion-group{"class" => active_user_sidebar_section?(:user)}
        .accordion-heading
          %a.accordion-toggle{"href" => root_path} My #{t('g.site_name')}

        .accordion-body
          .accordion-inner
            %ul.nav.nav-stacked
              %li{"class" => active_page?('home#dashboard')}=link_to "Dashboard", root_path
              %li{"class" => active_page?('notifications#index')}
                %a{"href" => notifications_path}
                  Notifications
                  - if current_user.unread_notification_count > 0
                    %span.badge= current_user.unread_notification_count

              %li{"class" => active_page?('saved_searches#index')}=link_to "Saved Searches", saved_searches_path

      - current_user.organizations.each do |organization|
        .accordion-group{"class" => active_user_sidebar_section?(:organization, organization)}
          .accordion-heading
            %a.accordion-toggle{"href" => admin_organization_path(organization)}= organization.name
          .accordion-body
            .accordion-inner
              %ul.nav.nav-stacked
                %li{"class" => !active_page?("organization_projects#new") && active_page?("organization_projects")}
                  =link_to "Projects", organization_projects_path(organization)
                - if can? :perform_user_actions_on, organization
                  %li{"class" => active_page?("form_templates")}
                    =link_to "Form Templates", organization_form_templates_path(organization)
                  %li{"class" => active_page?("organization_vendor_registrations")}
                    =link_to "Vendor Registrations", organization_vendor_registrations_path(organization)
                - if can? :admin, organization
                  %li{"class" => user_sidebar_settings_active?(:organization, organization)}
                    %a{"href" => edit_organization_path(organization)} Admin
                %li
                  %a{"href" => organization_path(organization)}
                    View public profile
                    %i.icon-share-alt

      - current_user.vendors.each do |vendor|
        .accordion-group{"class" => active_user_sidebar_section?(:vendor, vendor)}
          .accordion-heading
            %a.accordion-toggle{"href" => admin_vendor_path(vendor)}= vendor.name
          .accordion-body
            .accordion-inner
              %ul.nav.nav-stacked
                %li{"class" => active_page?("vendor_bids")}
                  =link_to "Bids", vendor_bids_path(vendor)
                %li{"class" => active_page?("vendor_registrations")}
                  =link_to "Registrations", vendor_registrations_path(@vendor)
                %li{"class" => active_page?("vendors#edit")}
                  %a{"href" => edit_vendor_path(@vendor)}
                    Vendor Profile
                    - if vendor.profile_incomplete?
                      %span.badge.badge-warning Incomplete
                %li{"class" => user_sidebar_settings_active?(:vendor, vendor)}
                  =link_to "Admin", members_vendor_path(vendor)

      - if !current_user.completed_registration
        .alert.alert-info
          Hey there, it looks like you haven't completed your registration yet. Do you still need to register
          as a <a href="#{new_vendor_path}">vendor</a> or an <a href="#{new_organization_path}">organization</a>?

  .span9
    = yield