config/routes.rb
ProcureIo::Application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

  root to: 'home#index', constraints: Clearance::Constraints::SignedOut.new
  root to: 'home#dashboard', constraints: Clearance::Constraints::SignedIn.new, as: :dashboard

  get 'for_vendors' => 'home#for_vendors'

  #### Clearance routes
  resources :passwords,
    :controller => 'clearance/passwords',
    :only => [:create, :new]

  resource :session,
    :controller => 'clearance/sessions',
    :only => [:create, :new, :destroy]

  resources :users,
    :controller => 'users',
    :only => [:create, :new] do
      resource :password,
        :controller => 'clearance/passwords',
        :only => [:create, :edit, :update]

      get 'accept_invite', on: :member
      post 'accept_invite' => 'users#post_accept_invite', on: :member
    end

  namespace :god do
    post 'login_as'
  end

  get '/sign_in' => 'clearance/sessions#new', :as => 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', :as => 'sign_out'
  get '/sign_up' => 'users#new', :as => 'sign_up'
  #### end clearance routes

  get 'settings/profile' => 'settings#profile', as: :settings_profile
  post 'settings/profile' => 'settings#post_profile'
  get 'settings/notifications' => 'settings#notifications', as: :settings_notifications
  post 'settings/notifications' => 'settings#post_notifications'
  get 'settings/account' => 'settings#account', as: :settings_account
  post 'settings/account' => 'settings#post_account'

  resources :notifications, only: [:index, :update]

  resources :saved_searches, only: [:index, :create, :destroy]

  resources :vendors do
    get 'profile', on: :member
    post 'profile' => 'vendors#post_profile', on: :member
    get 'admin', on: :member
    get 'members', on: :member
    post 'member' => 'vendors#add_member', on: :member
    delete 'member' => 'vendors#remove_member', on: :member
    post 'assign_ownership', on: :member
    delete 'leave', on: :member

    resources :bids, controller: :vendor_bids
    resources :registrations, controller: :vendor_registrations
  end

  resources :watches, only: [:create]

  resources :projects do
    get 'created', on: :member
    get 'admin', on: :member
    get 'teams' => 'projects#teams', on: :member
    post 'team' => 'projects#add_team', on: :member
    delete 'team' => 'projects#remove_team', on: :member
    get 'reviewer_leaderboard' => 'projects#reviewer_leaderboard', on: :member
    get 'review_mode' => 'projects#review_mode', on: :member
    post 'review_mode' => 'projects#post_review_mode', on: :member
    get 'comments', on: :member
    get 'import_csv' => 'projects#import_csv', on: :member
    post 'import_csv' => 'projects#post_import_csv', on: :member
    get 'export_csv' => 'projects#export_csv', on: :member
    post 'export_csv' => 'projects#post_export_csv', on: :member
    get 'response_fields' => 'projects#response_fields', on: :member

    resources :reports, only: [] do
      get 'bids_over_time', on: :collection
      get 'impressions', on: :collection
      get 'response_field', on: :collection
    end

    resources :bids do
      post 'edit' => 'bids#post_edit', on: :member
      get 'emails', on: :collection
      put 'batch', on: :collection
      get 'reviews', on: :member
      post 'read_notifications', on: :member
    end

    resources :project_revisions, only: [:show] do
      post 'restore', on: :member
    end

    resources :project_attachments, only: [:destroy]

    resources :amendments
    resources :labels, only: [:create, :destroy, :update]
    resources :questions
  end

  resources :response_fields do
    put 'batch', on: :collection
    delete 'response' => 'response_fields#delete_response', on: :member
  end

  resources :comments

  get '404' => 'errors#not_found'

  resources :organizations, path: '', except: [:index, :new, :create] do
    get 'admin', on: :member
    get 'members', on: :member

    resources :teams do
      get 'members', on: :member
      post 'member' => 'teams#add_member', on: :member
      delete 'member' => 'teams#remove_member', on: :member
    end

    resources :form_templates do
      # post 'create_from_existing', on: :collection
      # get 'pick' => 'form_templates#pick_template', on: :collection
      # get 'preview', on: :member
      # post 'use', on: :member
    end

    resources :projects, controller: :organization_projects
    resources :registrations, controller: :organization_registrations
    resources :vendor_registrations, controller: :organization_vendor_registrations do
      post 'approve', on: :member
      post 'reject', on: :member
    end
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                      :integer          not null, primary key
#  title                   :string(255)
#  slug                    :string(255)
#  body                    :text
#  bids_due_at             :datetime
#  organization_id         :integer
#  posted_at               :datetime
#  poster_id               :integer
#  total_comments          :integer          default(0)
#  form_options            :text
#  abstract                :text
#  featured                :boolean
#  question_period_ends_at :datetime
#  review_mode             :integer          default(1)
#  total_submitted_bids    :integer          default(0)
#  solicit_bids            :boolean
#  review_bids             :boolean
#  created_at              :datetime
#  updated_at              :datetime
#

require_dependency 'enum'

class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  include ActionView::Helpers::TextHelper
  include Behaviors::Postable
  include Behaviors::Watchable
  include Behaviors::TargetableForEvents
  include Behaviors::ResponseFieldable

  attr_accessor :current_user

  self.cache_timestamp_format = :nsec

  is_impressionable

  belongs_to :organization

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :organization, presence: true
  validates :review_mode, presence: true
  validates :abstract, length: { maximum: 500 }

  has_many :bids, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :labels, dependent: :destroy
  has_many :amendments, dependent: :destroy
  has_many :project_revisions, -> { order('created_at DESC') }, dependent: :destroy
  has_many :project_attachments, dependent: :destroy
  has_and_belongs_to_many :tags, after_add: :touch_self, after_remove: :touch_self
  has_and_belongs_to_many :teams, -> { uniq }, after_add: :after_team_added

  after_create :add_owners_team!
  after_update :generate_project_revisions_if_body_changed!
  before_save :generate_abstract_if_blank!

  scope :featured, -> { where(featured: true) }
  scope :open_for_bids, -> { where("bids_due_at IS NULL OR bids_due_at > ?", Time.now) }
  scope :join_tags, -> { joins("LEFT JOIN projects_tags ON projects.id = projects_tags.project_id INNER JOIN tags ON tags.id = projects_tags.tag_id") }

  has_searcher starting_query: Project.open_for_bids.posted

  pg_search_scope :full_search, against: [:title, :body],
                                associated_against: { amendments: [:title, :body],
                                                      questions: [:body, :answer_body],
                                                      tags: [:name] },
                                using: {
                                  tsearch: {prefix: true}
                                }

  calculator :total_comments do comments end
  calculator :total_submitted_bids do
    bids.submitted.count
  end

  def question_period_over?
    question_period_ends_at && (question_period_ends_at < Time.now)
  end

  def team_choices
    q = organization.teams.not_owners
    q = q.where("id NOT IN (?)", teams.pluck(:id)) if teams.any?
    q
  end

  def self.review_modes
    @review_modes ||= Enum.new(:stars, :one_through_five)
  end

  def self.add_params_to_query(query, params, args = {})
    if !params[:q].blank?
      query = query.full_search(params[:q])
    end

    if !params[:category].blank?
      query = query.join_tags.where("tags.name = ?", params[:category])
    end

    if params[:posted_after]
      query = query.where(posted_at: params[:posted_after]..Time.now)
    end

    direction = params[:direction] == 'asc' ? 'asc' : 'desc'

    if params[:sort] == "posted_at" || params[:sort].blank?
      query = query.order("posted_at #{direction}")

    elsif params[:sort] == "bids_due_at"
      query = query.order("bids_due_at #{direction}")

    elsif params[:sort] == "title"
      query = query.order("title #{direction}")

    elsif params[:sort] == "total_submitted_bids" && args[:allow_additional_sort_options]
      query = query.order("total_submitted_bids #{direction}")

    end

    query
  end

  def unread_bids_for_user(user)
    bids.submitted.joins("LEFT JOIN bid_reviews on bid_reviews.bid_id = bids.id AND bid_reviews.user_id = #{user.id}")
                  .where("bid_reviews.read = false OR bid_reviews.read IS NULL")
  end

  def open_for_bids?
    posted? && (!bids_due_at || (bids_due_at > Time.now))
  end

  def status
    if bids_due_at && open_for_bids?
      :open_with_due_date

    elsif !bids_due_at && open_for_bids?
      :open_for_bids

    elsif bids.awarded.count > 0
      :awards_made

    elsif bids_due_at && (bids_due_at < Time.now) && !open_for_bids?
      :closed_with_due_date

    elsif !posted_at
      :not_yet_posted
    end
  end

  def status_badge_class
    case status
    when :not_yet_posted
      ''
    when :open_with_due_date, :open_for_bids
      'badge-success'
    when :closed_with_due_date
      'badge-important'
    when :awards_made
      'badge-info'
    end
  end

  def status_text
    case status
    when :not_yet_posted
      I18n.t('g.not_yet_posted')
    when :open_with_due_date
      I18n.t('g.open_for_bids')
    when :open_for_bids
      I18n.t('g.open_for_bids')
    when :closed_with_due_date
      I18n.t('g.bids_closed')
    when :awards_made
      I18n.t('g.awards_made')
    end
  end

  def long_status_text
    case status
    when :not_yet_posted
      I18n.t('g.not_yet_posted')
    when :open_with_due_date
      I18n.t("g.bids_due_on_date", date: bids_due_at.to_formatted_s(:readable))
    when :open_for_bids
      I18n.t('g.open_for_bids')
    when :closed_with_due_date
      I18n.t("g.bids_were_due_on_date", date: bids_due_at.to_formatted_s(:readable))
    when :awards_made
      I18n.t('g.awards_made')
    end
  end


  private
  def generate_project_revisions_if_body_changed!
    return unless body_changed?
    project_revisions.create(body: body_was, saved_by_user: current_user)
  end

  def after_team_added(team)
    return if team.is_owners
    create_events(:added_your_team_to_project, team.users, self)
  end

  def add_owners_team!
    teams << organization.owners_team
  end

  def generate_abstract_if_blank!
    return unless self.abstract.blank? && !self.body.blank?
    self.abstract = truncate(strip_tags(self.body).gsub(/\n/, ' '), length: 350, omission: "...")
  end

  handle_asynchronously :after_team_added
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # Load
  load_resource


  before_filter only: [:new] { |c| c.authorize! :create, Project }
  before_filter only: [:admin] { |c| c.authorize! :collaborate_on, @project }
  before_filter only: [:import_csv, :post_import_csv] { |c| c.authorize! :import_bids, @project }
  before_filter only: [:export_csv, :post_export_csv] { |c| c.authorize! :export_bids, @project }
  before_filter only: [:review_mode, :post_review_mode] { |c| c.authorize! :change_review_mode, @project }
  before_filter only: [:teams, :add_team, :remove_team] { |c| c.authorize! :manage_teams, @project }
  before_filter only: [:edit, :update] { |c| c.authorize! :update, @project }
  before_filter :ensure_user_has_permission_to_create_project, only: :create

  def index
    search_results = Project.searcher(params)
    @projects = search_results[:results]
    @filter_params = { category: params[:category], q: params[:q] }

    respond_to do |format|
      format.html do
        @bootstrap_data = serialized(@projects, SearchProjectSerializer, meta: search_results[:meta])
      end

      format.json { render_serialized(@projects, SearchProjectSerializer, meta: search_results[:meta]) }
      format.rss { render layout: false }
    end
  end

  # generic landing page for the backend
  def admin
    redirect_to (can? :update, @project) ? edit_project_path : project_bids_path(@project)
  end

  def comments
    authorize! :comment_on, @project
    current_user.read_notifications(@project, :project_comment)
    @comments_json = serialized(@project.comments).to_json
  end

  def teams
    @teams = @project.teams.order("teams.name").references(:teams)
  end

  def add_team
    @team = @project.organization.teams.find(params[:team_id])
    @project.teams << @team
    redirect_to :back
  end

  def remove_team
    @team = @project.organization.teams.find(params[:team_id])
    @project.teams.delete(@team) unless @team.is_owners
    redirect_to :back
  end

  def show
    authorize! :read, @project
    current_user.read_notifications(@project, :project_amended, :added_your_team_to_project, :question_answered) if current_user
    @questions = @project.questions
    impressionist(@project)
  end

  def new
  end

  def create
    @project.assign_attributes(project_params)

    if @project.save
      @project.teams << current_user.highest_ranking_team_for_organization(@project.organization)
      redirect_to created_project_path(@project)
    else
      render "new"
    end
  end

  def created
  end

  def edit
    current_user.read_notifications(@project, :added_your_team_to_project)
  end

  def update
    if @project.update_attributes(project_params)
      @project.tags = []

      params[:project][:tags].split(",").each do |name|
        @tag = Tag.where("lower(name) = ?", name.strip.downcase).first || Tag.create(name: name.strip)
        @project.tags << @tag
      end

      params[:new_attachments].each do |new_attachment|
        @project.project_attachments.create(upload: new_attachment)
      end

      redirect_to edit_project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @project
    @project.destroy
    redirect_to root_path
  end

  def import_csv
  end

  def post_import_csv
    file_contents = params.delete(:file).read
    importer = CsvBidImporter.delay.new(@project, file_contents, params, current_user)
    flash[:success] = "Hang tight, we're importing your bids. Give us a minute, and we'll notify you when we're done."
    redirect_to project_bids_path(@project)
  end

  def export_csv
  end

  def post_export_csv
    require 'csv'
    @bids = @project.bids.submitted

    bids_csv = CSV.generate do |csv|
      headers = ["Vendor Name"]
      headers.push *@project.response_fields.map(&:label)
      headers.push "Labels", "Status", "Submitted At"
      csv << headers

      @bids.each do |bid|
        bid_row = [(bid.vendor ? bid.vendor.name : "-")]
        responses = bid.responses

        @project.response_fields.each do |response_field|
          response = responses.select { |br| br.response_field_id == response_field.id }[0]
          bid_row.push(response ? response.value : '')
        end

        bid_row.push bid.labels.map(&:name).join(', '), bid.text_status, bid.submitted_at
        csv << bid_row
      end
    end

    send_data(bids_csv, type: 'test/csv', filename: "#{@project.title.parameterize.underscore}_bids_export_#{Time.now.strftime("%m_%d_%y")}.csv")
  end

  def review_mode
  end

  def post_review_mode
    @project.update_attributes pick(params[:project], :review_mode)
    flash[:success] = t('g.updated_project_review_mode')
    redirect_to review_mode_project_path(@project)
  end

  def response_fields
    authorize! :manage_response_fields, @project
  end

  def reviewer_leaderboard
    bid_ids = @project.bids.pluck(:id)

    @leaderboard = BidReview.select("user_id, COUNT(user_id) as review_count").where("bid_id IN (?)", bid_ids).group("user_id")

    if @project.review_mode == Project.review_modes[:stars]
      @leaderboard = @leaderboard.where(starred: true)
    else # one_through_five
      @leaderboard = @leaderboard.where("rating IS NOT NULL")
    end

    @leaderboard = @leaderboard.order("review_count DESC").paginate(page: params[:page])
  end

  private
  def project_params(*extra_params)
    filtered_params = params.require(:project).permit(:featured, :title, :abstract, :body, :bids_due_at,
                                                      :question_period_ends_at, :posted, *extra_params)

    if !filtered_params[:body].blank?
      require 'sanitize'
      filtered_params[:body] = Sanitize.clean(filtered_params[:body], Sanitize::Config::RELAXED)
    end

    {current_user: current_user}.merge(filtered_params)
  end

  def ensure_user_has_permission_to_create_project
    @project.organization_id = params[:project][:organization_id]

    if !(can? :create, @project)
      # @todo this is pretty annoying behavior.
      flash.now[:error] = "Sorry, you don't have permission to create a new project for that organization."
      render "new"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_officer_nav.html.haml
- provide :page_title, @project.title

%h3
  = @project.title
  %small
    %span.badge.badge-indicator{"class" => @project.status_badge_class}
    = @project.long_status_text

.button-nav
  %ul.nav.nav-tabs
    - if can? :read_bids, @project
      %li{"class" => active_page?("bids")}
        %a{"href" => project_bids_path(@project)}
          = t('g.review_bids')
          - if @project.bids.submitted.join_my_bid_review(current_officer.id).unread.count > 0
            %span.badge.badge-info= @project.bids.submitted.join_my_bid_review(current_officer.id).unread.count

    - if GlobalConfig.instance[:questions_enabled] && (can? :answer_questions, @project)
      %li{"class" => active_page?("questions#index")}
        %a{"href" => project_questions_path(@project)}
          = t('g.q_and_a')
          - if @project.questions.unanswered.count > 0
            %span.badge.badge-info= @project.questions.unanswered.count


    - if GlobalConfig.instance[:comments_enabled] && (can? :read_and_write_project_comments, @project)
      %li{"class" => active_page?("projects#comments")}
        =link_to t('g.discuss'), comments_project_path(@project)

    - if can_view_subnav?("stats")
      %li{"class" => active_subnav?("stats")}
        %a{"href" => (can? :access_reports, @project) ? bids_over_time_project_reports_path(@project) : reviewer_leaderboard_project_path(@project)}
          %span= t('g.stats')

    %li{"class" => active_subnav?("admin")}
      =link_to t('g.admin'), project_collaborators_path(@project)

  .button-nav-group
    != watch_button @project, class: "dropdown-left"

    %a.btn.view-project-button{"href" => project_path(@project)}
      %i.icon-share-alt

- if active_subnav?("stats")
  .subnav.project-subnav
    %ul.nav.nav-pills
      - if can? :access_reports, @project
        %li{"class" => "#{active_page?("reports")} #{if !@project.posted? then 'disabled' end}"}
          = link_to t('g.reports'), @project.posted? ? bids_over_time_project_reports_path(@project) : '#', |
              "data-toggle" => if !@project.posted? then "tooltip" end, |
              "title" => if !@project.posted? then t('.reports_available_after_post') end

      - if GlobalConfig.instance[:reviewer_leaderboard_enabled]
        %li{"class" => active_page?("projects#reviewer_leaderboard")}
          %a{"href" => reviewer_leaderboard_project_path(@project)}
            = t('g.reviewer_leaderboard')

- if active_subnav?("admin")
  .subnav.project-subnav
    %ul.nav.nav-pills
      - if can? :edit_project_details, @project
        %li{"class" => active_page?("projects#edit") || active_page?("amendments") || active_page?("project_revisions")}
          %a{"href" => edit_project_path(@project)}
            = t('g.edit_posting')

      - if can? :manage_response_fields, @project
        %li{"class" => active_page?("projects#response_fields")}
          %a{"href" => response_fields_project_path(@project)}= t('g.edit_response_fields')

      - if can? :change_review_mode, @project
        %li{"class" => active_page?("projects#review_mode")}
          %a{"href" => review_mode_project_path(@project)}= t('g.change_review_mode')

      %li{"class" => active_page?("collaborators#index")}
        =link_to t('g.collaborators'), project_collaborators_path(@project)

      - if can? :import_bids, @project
        %li{"class" => active_page?("projects#import_csv")}
          =link_to t('g.import_bids_from_csv'), import_csv_project_path(@project)

      - if can? :export_bids, @project
        %li{"class" => active_page?("projects#export_csv")}
          =link_to t('g.export_bids'), export_csv_project_path(@project)

app/views/projects/_question_period_over.html.haml
%small The question period ended on #{@project.question_period_ends_at.to_formatted_s(:readable_dateonly)}.

app/views/projects/created.html.haml
- provide :page_title, t('g.created_project')

!=page_header t('g.created_project')

.alert.alert-success
  Congrats! You successfully created the project, and we took the liberty of adding the #{current_user.highest_ranking_team_for_organization(@project.organization).name} team to collaborate.

%h4 What next?

%ol
  - if @project.solicit_bids
    %li
      Write a <a href="#{edit_project_path}">statement of work</a>.
    %li
      Create your <a href="#{response_fields_project_path}">response form</a>. You can use a pre-defined template, or create a form from scratch.
  - else
    %li
      Gather your bids into a CSV file and <a href="#{import_csv_project_path}">import them</a> into your project.
  %li <a href="#{teams_project_path}">Add teammates</a> to collaborate with you.


.form-actions
  %a.btn.btn-primary{"href" => admin_project_path} Go to the project &rarr;

app/views/projects/import_csv.html.haml
- provide :page_action, t('g.import_bids')

= render "projects/header_backend"

.alert.alert-warning= t('g.experimental_follow_steps_html')

.readable-width
  = form_tag import_csv_project_path(@project), multipart: true do

    .control-group
      %label.label-required= t('g.options')

      %label.checkbox
        %input{"type" => "checkbox", "name" => "override_response_fields", "data-toggle-class" => "hide", "data-target" => ".response-fields-help", "disabled" => if @project.bids.count > 0 then true end, "checked" => if @project.bids.count == 0 then true end}
        = t('.override_response_fields')
        - if @project.response_fields.count > 0
          .badge.badge-info.response-fields-help{"class" => if @project.bids.count != 0 then "hide" end}= t('.will_destroy_existing_response_fields')
        - else
          .badge.badge-success Recommended

        - if @project.bids.count > 0
          %span.badge.badge-info= t('.not_possible_bids_already_exist')

        %span.help-block.response-fields-help{"class" => if @project.bids.count == 0 then "hide" end}
          = t('.response_fields_help_html')
          != @project.response_fields.map {|rf| "<code>#{rf.label}</code>"}.join(", ")

      %label.checkbox
        %input{"type" => "checkbox", "name" => "associate_vendor_account", "data-toggle-class" => "hide", "data-target" => "#vendor-account-help"}
        = t('.associate_vendor_account')
        %span.help-block.hide#vendor-account-help= t('.vendor_account_help_html')

    .control-group
      %label.label-required= t('.label_imported_bids_as')
      %input{"type" => "text", "name" => "label_imported_bids", "value" => t('g.imported_from_csv')}
      %span.help-block= t('.leave_blank_for_no_label')

    .control-group
      %label.label-required{"for" => "file"}= t('g.select_the_file')
      != fileupload_tag :file

    .form-actions
      %button.btn.btn-primary= t('g.import')

app/views/projects/index.html.haml
- provide :page_title, t('g.browse_projects')

- if !signed_in?
  .alert.alert-info
    %p Want to ask questions, track projects, or just ready to bid? <a href="#{sign_up_path}">Sign up</a> in seconds!

!=page_header t('g.browse_projects')

#project-page.project-list.search-page
  :javascript
    new ProcureIo.Backbone.ProjectPage({
      allCategories: #{Tag.all_for_select2.to_json},
      bootstrapData: #{bootstrap @bootstrap_data.to_json}
    });

app/views/projects/show.html.haml
- provide :page_title, @project.title

- if !signed_in?
  .alert.alert-info= t('.not_logged_in_alert.line_html', sign_in: link_to(t('.not_logged_in_alert.sign_in'), sign_in_path), sign_up: link_to(t('.not_logged_in_alert.sign_up'), sign_up_path))

= render "projects/header_frontend"

.row-fluid
  .span7
    - if !@project.abstract.blank?
      %h4= Project.human_attribute_name(:abstract)
      %p= @project.abstract

    %h4
      = t('g.description')
      - if @project.amendments.posted.any?
        %small= t('.jump_to_amendments_html', count: @project.amendments.posted.length)

    %p= simple_format @project.body

    - if @project.project_attachments.any?
      %h4 Attachments
      %ul
        - @project.project_attachments.each do |project_attachment|
          %li= link_to project_attachment.upload.file.filename, project_attachment.upload.url

    - if @project.amendments.posted.any?
      #amendments
        %h4= t('g.amendments')
        - @project.amendments.posted.each do |amendment|
          %h5
            = amendment.title
            %small= t('g.posted_on_date', date: amendment.posted_at.to_formatted_s(:readable_dateonly))
          %p!= amendment.body

  .span5
    - if current_vendor
      %h4 Bids

      %ul.ul-unstyled
        - current_user.bids.where(project: @project).each do |bid|
          %li
            = link_to bid.vendor.name + " " + bid.identifier, vendor_bid_path(bid.vendor, bid)
            != bid.badged_text_status

      .form-actions
        = form_for [@project, Bid.new], method: :post, html: { class: 'form-no-margin' } do |f|
          = vendor_selector(f)
          %button.btn.btn-primary New Bid

    %h4
      = t('g.questions')

      - if signed_in?
        - if can? :ask_question, @project
          %small
            %a#ask-question-toggle.btn.btn-small{"data-toggle" => "collapse", "data-target" => "#ask-question"} Ask question
            - if @question_period_ends_at
              Questions due #{@project.question_period_ends_at.to_formatted_s(:readable)}
        - else
          = render "question_period_over"
      - else
        - if @project.question_period_over?
          = render "question_period_over"

    - if signed_in?
      #ask-question.collapse
        = form_for [@project, Question.new], remote: true do |f|
          = f.text_area :body, cols: nil, rows: 4, class: "span12"
          %br
          = f.submit t('g.submit'), class: "btn btn-primary", "data-loading-text" => t('g.submitting')

    #questions-list
      - if @questions.count == 0
        #no-questions= t('.no_questions')
      - @questions.each do |question|
        = render "questions/question", question: question

app/views/projects/teams.html.haml
- provide :page_action, t('g.teams')

= render "projects/header_backend"

%h4 Teams with access

.row-fluid
  .span6
    %table.table
      %thead
        %tr
          %th Name
          %th # of Members
          %th Actions

      %tbody#project-teams-tbody
        - @teams.each do |team|
          %tr
            %td= link_to team.name, edit_organization_team_path(@project.organization, team)
            %td= team.organization_team_members.count
            %td
              - if team.is_owners
                Owners team has access to all projects.
              - else
                = link_to "Add members to team", edit_organization_team_path(@project.organization, team), class: "btn btn-mini"
                = link_to "Remove", team_project_path(@project, team_id: team.id), method: :delete, class: "btn btn-danger btn-mini"


%h5 Add Existing Team

= form_tag team_project_path(@project), method: :post do

  .control-group
    %select{"name" => "team_id"}
      - @project.team_choices.each do |team|
        %option{"value" => team.id}= team.name
    .help-block or create a <a href="#{new_organization_team_path(@project.organization)}">new team</a>

  %button.btn.btn-primary= I18n.t('g.submit')

app/views/projects/wufoo_instructions.html.haml
= render "projects/officer_nav"

= render layout: "projects/admin_sidebar" do
  .alert.alert-warning
    <strong>Howdy!</strong> This feature is pretty experimental, so if you do choose to proceed, be sure to follow the steps below.

  .readable-width
    %p
      <strong>1.</strong> Your <a href="#{project_response_fields_path(@project)}">response field labels</a> need to match the field labels on your Wufoo form, like this:
      = image_tag "matching-labels.png"

    %p
      <strong>2.</strong> In addition, your Wufoo form should have fields titled <code>Email</code> and <code>Name</code>.

    %p
      <strong>3.</strong> In the Wufoo admin panel, find your form and add a new Webhook notification. Your webhook URL should be <code>#{wufoo_project_bids_url(@project, auth_token: current_officer.authentication_token)}</code>, and be sure to check the box labeled "Include Field and Form Structures with Entry Data".

    %p
      <strong>4.</strong> Sit back and watch the applications roll in!