config/routes.rb
ProcureIo::Application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

  root to: 'home#index', constraints: Clearance::Constraints::SignedOut.new
  root to: 'home#dashboard', constraints: Clearance::Constraints::SignedIn.new, as: :dashboard

  get 'for_vendors' => 'home#for_vendors'

  #### Clearance routes
  resources :passwords,
    :controller => 'clearance/passwords',
    :only => [:create, :new]

  resource :session,
    :controller => 'clearance/sessions',
    :only => [:create, :new, :destroy]

  resources :users,
    :controller => 'users',
    :only => [:create, :new] do
      resource :password,
        :controller => 'clearance/passwords',
        :only => [:create, :edit, :update]

      get 'accept_invite', on: :member
      post 'accept_invite' => 'users#post_accept_invite', on: :member
    end

  namespace :god do
    post 'login_as'
  end

  get '/sign_in' => 'clearance/sessions#new', :as => 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', :as => 'sign_out'
  get '/sign_up' => 'users#new', :as => 'sign_up'
  #### end clearance routes

  get 'settings/profile' => 'settings#profile', as: :settings_profile
  post 'settings/profile' => 'settings#post_profile'
  get 'settings/notifications' => 'settings#notifications', as: :settings_notifications
  post 'settings/notifications' => 'settings#post_notifications'
  get 'settings/account' => 'settings#account', as: :settings_account
  post 'settings/account' => 'settings#post_account'

  resources :notifications, only: [:index, :update]

  resources :saved_searches, only: [:index, :create, :destroy]

  resources :vendors do
    get 'profile', on: :member
    post 'profile' => 'vendors#post_profile', on: :member
    get 'admin', on: :member
    get 'members', on: :member
    post 'member' => 'vendors#add_member', on: :member
    delete 'member' => 'vendors#remove_member', on: :member
    post 'assign_ownership', on: :member
    delete 'leave', on: :member

    resources :bids, controller: :vendor_bids
    resources :registrations, controller: :vendor_registrations
  end

  resources :watches, only: [:create]

  resources :projects do
    get 'created', on: :member
    get 'admin', on: :member
    get 'teams' => 'projects#teams', on: :member
    post 'team' => 'projects#add_team', on: :member
    delete 'team' => 'projects#remove_team', on: :member
    get 'reviewer_leaderboard' => 'projects#reviewer_leaderboard', on: :member
    get 'review_mode' => 'projects#review_mode', on: :member
    post 'review_mode' => 'projects#post_review_mode', on: :member
    get 'comments', on: :member
    get 'import_csv' => 'projects#import_csv', on: :member
    post 'import_csv' => 'projects#post_import_csv', on: :member
    get 'export_csv' => 'projects#export_csv', on: :member
    post 'export_csv' => 'projects#post_export_csv', on: :member
    get 'response_fields' => 'projects#response_fields', on: :member

    resources :reports, only: [] do
      get 'bids_over_time', on: :collection
      get 'impressions', on: :collection
      get 'response_field', on: :collection
    end

    resources :bids do
      post 'edit' => 'bids#post_edit', on: :member
      get 'emails', on: :collection
      put 'batch', on: :collection
      get 'reviews', on: :member
      post 'read_notifications', on: :member
    end

    resources :project_revisions, only: [:show] do
      post 'restore', on: :member
    end

    resources :project_attachments, only: [:destroy]

    resources :amendments
    resources :labels, only: [:create, :destroy, :update]
    resources :questions
  end

  resources :response_fields do
    put 'batch', on: :collection
    delete 'response' => 'response_fields#delete_response', on: :member
  end

  resources :comments

  get '404' => 'errors#not_found'

  resources :organizations, path: '', except: [:index, :new, :create] do
    get 'admin', on: :member
    get 'members', on: :member

    resources :teams do
      get 'members', on: :member
      post 'member' => 'teams#add_member', on: :member
      delete 'member' => 'teams#remove_member', on: :member
    end

    resources :form_templates do
      # post 'create_from_existing', on: :collection
      # get 'pick' => 'form_templates#pick_template', on: :collection
      # get 'preview', on: :member
      # post 'use', on: :member
    end

    resources :projects, controller: :organization_projects
    resources :registrations, controller: :organization_registrations
    resources :vendor_registrations, controller: :organization_vendor_registrations do
      post 'approve', on: :member
      post 'reject', on: :member
    end
  end
end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  slug           :string(255)
#  email          :string(255)
#  address_line_1 :string(255)
#  address_line_2 :string(255)
#  city           :string(255)
#  state          :string(255)
#  zip            :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  phone_number   :string(255)
#  contact_name   :string(255)
#

class Vendor < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  include Behaviors::TargetableForEvents

  AUTOFILLABLE_FIELDS = [:address_line_1, :address_line_2, :city, :state, :zip]

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :email, presence: true, email: true

  has_many :bids, dependent: :destroy
  has_many :vendor_team_members, dependent: :destroy
  has_many :users,
           -> { select('users.*, vendor_team_members.owner as owner').uniq },
           through: :vendor_team_members
  has_many :vendor_registrations

  # after_update do
  #   bids.update_all(updated_at: Time.now)
  # end

  def owner
    users.where(vendor_team_members: { owner: true }).first
  end

  def profile_incomplete?
    address_line_1.blank? ||
    city.blank? ||
    state.blank? ||
    zip.blank?
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # Load
  load_resource

  # Authorize
  before_filter :authorize, only: [:new, :create]
  before_filter except: [:new, :create] { |c| c.authorize! :collaborate_on, @vendor }

  def show
  end

  def admin
    redirect_to vendor_bids_path(@vendor)
  end

  def new
  end

  def create
    if @vendor.update_attributes(vendor_params)
      @vendor.vendor_team_members.create(user: current_user, owner: true)
      flash[:success] = "Your vendor profile has been created. Why don't you add some " +
                        "<a href='#{members_vendor_path(@vendor)}'>team members</a>?"
      redirect_to admin_vendor_path(@vendor)
    else
      render :new
    end
  end

  def edit
    current_user.read_notifications(@vendor)
  end

  def update
    if @vendor.update_attributes(vendor_params)
      flash[:success] = "Profile updated successfully."
      redirect_to edit_vendor_path(@vendor)
    else
      render :edit
    end
  end

  def destroy
    @vendor.destroy
    redirect_to root_path
  end

  def members
  end

  def add_member
    @user = User.where(email: params[:email]).first ||
            User.invite!(params[:email], current_user)

    if @user
      @vendor.users << @user
      @user = @vendor.users.where(id: @user.id).first # add 'owner' attribute when selecting
    end
  end

  def remove_member
    @vendor_team_member = @vendor.vendor_team_members.where(user_id: params[:user_id]).first
    @vendor.vendor_team_members.delete(@vendor_team_member) unless @vendor_team_member.owner
    render_json_success
  end

  def assign_ownership
    if @vendor.owner == current_user
      @vendor.vendor_team_members.update_all(owner: false)
      @vendor.vendor_team_members.where(user_id: params[:user_id]).first.update_attributes(owner: true)
    end

    redirect_to :back
  end

  def leave
    if @vendor.vendor_team_members.count < 2
      flash[:error] = "Can't remove yourself, as you're the last team member. Did you want to destroy this vendor account instead?"
      return redirect_to edit_vendor_path
    end

    @vendor.vendor_team_members.where(user_id: current_user.id, owner: false).first.destroy
    redirect_to root_path
  end

  private
  def vendor_params
    params.require(:vendor).permit(:name, :email, :address_line_1, :address_line_2, :city, :state, :zip)
  end
end

app/views/vendors/_form.html.haml
= simple_form_for @vendor, validate: true do |f|

  = f.input :name, label: "Business Name", hint: "The name of your business. e.g. 'Department of Better Technology, LLC'."
  = f.input :contact_name
  = f.input :email, label: "Contact Email", hint: 'A public email address for your business.'
  = f.input :phone_number
  = f.input :address_line_1
  = f.input :address_line_2
  = f.input :city
  = f.input :state
  = f.input :zip

  .form-actions
    = f.button :submit, class: 'btn-primary'
    - if @vendor.new_record?
      %span.help-inline Or did you want to <a href="#{new_organization_path}">create an organization</a>?

app/views/vendors/_member.html.haml
%tr
  %td
    = user.name
    - if user.owner
      %i.icon-star
  %td= user.email
  %td
    - if !user.owner
      - if user == current_user
        %a.btn.btn-small.btn-danger{"href" => leave_vendor_path(@vendor), "data-method" => "delete", "data-confirm" => "Are you sure?"} Leave vendor
      - else
        %a.btn.btn-small.btn-danger.js-remove-member{"href" => member_vendor_path(@vendor, user_id: user.id), "data-method" => "delete", "data-remote" => true, "data-loading-text" => "Removing..."}= I18n.t('g.remove')

      - if @vendor.owner == current_user
        %a.btn.btn-small{"href" => assign_ownership_vendor_path(@vendor, user_id: user.id), "data-method" => "post"} Transfer ownership

app/views/vendors/_member_table.html.haml
%table.table.table-nonfluid#member-table
  %thead
    %tr
      %th= User.human_attribute_name(:name)
      %th= User.human_attribute_name(:email)
      %th= t('g.actions')

  %tbody#members-tbody
    - @vendor.users.each do |user|
      = render "member", user: user

app/views/vendors/_subnav.html.haml
- provide :page_title, @vendor.name

%ul.nav.nav-tabs
  %li{"class" => active_page?("vendors#members")}
    =link_to "Members", members_vendor_path(@vendor)

app/views/vendors/edit.html.haml
- provide :page_action, "Edit info"

= render layout: "shared/user_sidebar" do

  = render "form"

  = link_to "Delete Vendor", vendor_path, method: :delete, data: { confirm: "Are you sure?" }

app/views/vendors/index.html.haml
- provide :page_action, t('g.vendors')

= render "admin/nav"

#searchable-table-page.search-page
  :javascript
    new ProcureIo.Backbone.SearchableTable({
      collection: ProcureIo.Backbone.VendorList,
      columns: [
        {
          name: "#{Vendor.human_attribute_name(:name)}",
          accessor: 'name',
          sortKey: 'name',
          defaultSort: 'asc'
        },
        {
          name: "#{User.human_attribute_name(:email)}",
          accessor: 'user.email',
          sortKey: 'email'
        }
      ]
    });

app/views/vendors/members.html.haml
- provide :page_action, "Members"

= render layout: "shared/user_sidebar" do

  = render "subnav"

  = render "vendors/member_table"

  %h5 Add Team Member

  %form#add_team_member{"action" => member_vendor_path(@vendor), "method" => "post", "data-remote" => "true"}
    .control-group
      %input{"type" => "text", "name" => "email", "placeholder" => I18n.t('g.email_address')}

    %button.btn.btn-primary{"data-loading-text" => "Adding..."} Add

app/views/vendors/new.html.haml
- provide :page_title, "New Vendor"
%h3 New Vendor

= render "form"