config/routes.rb
ProcureIo::Application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

  root to: 'home#index', constraints: Clearance::Constraints::SignedOut.new
  root to: 'home#dashboard', constraints: Clearance::Constraints::SignedIn.new, as: :dashboard

  get 'for_vendors' => 'home#for_vendors'

  #### Clearance routes
  resources :passwords,
    :controller => 'clearance/passwords',
    :only => [:create, :new]

  resource :session,
    :controller => 'clearance/sessions',
    :only => [:create, :new, :destroy]

  resources :users,
    :controller => 'users',
    :only => [:create, :new] do
      resource :password,
        :controller => 'clearance/passwords',
        :only => [:create, :edit, :update]

      get 'accept_invite', on: :member
      post 'accept_invite' => 'users#post_accept_invite', on: :member
    end

  namespace :god do
    post 'login_as'
  end

  get '/sign_in' => 'clearance/sessions#new', :as => 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', :as => 'sign_out'
  get '/sign_up' => 'users#new', :as => 'sign_up'
  #### end clearance routes

  get 'settings/profile' => 'settings#profile', as: :settings_profile
  post 'settings/profile' => 'settings#post_profile'
  get 'settings/notifications' => 'settings#notifications', as: :settings_notifications
  post 'settings/notifications' => 'settings#post_notifications'
  get 'settings/account' => 'settings#account', as: :settings_account
  post 'settings/account' => 'settings#post_account'

  resources :notifications, only: [:index, :update]

  resources :saved_searches, only: [:index, :create, :destroy]

  resources :vendors do
    get 'profile', on: :member
    post 'profile' => 'vendors#post_profile', on: :member
    get 'admin', on: :member
    get 'members', on: :member
    post 'member' => 'vendors#add_member', on: :member
    delete 'member' => 'vendors#remove_member', on: :member
    post 'assign_ownership', on: :member
    delete 'leave', on: :member

    resources :bids, controller: :vendor_bids
    resources :registrations, controller: :vendor_registrations
  end

  resources :watches, only: [:create]

  resources :projects do
    get 'created', on: :member
    get 'admin', on: :member
    get 'teams' => 'projects#teams', on: :member
    post 'team' => 'projects#add_team', on: :member
    delete 'team' => 'projects#remove_team', on: :member
    get 'reviewer_leaderboard' => 'projects#reviewer_leaderboard', on: :member
    get 'review_mode' => 'projects#review_mode', on: :member
    post 'review_mode' => 'projects#post_review_mode', on: :member
    get 'comments', on: :member
    get 'import_csv' => 'projects#import_csv', on: :member
    post 'import_csv' => 'projects#post_import_csv', on: :member
    get 'export_csv' => 'projects#export_csv', on: :member
    post 'export_csv' => 'projects#post_export_csv', on: :member
    get 'response_fields' => 'projects#response_fields', on: :member

    resources :reports, only: [] do
      get 'bids_over_time', on: :collection
      get 'impressions', on: :collection
      get 'response_field', on: :collection
    end

    resources :bids do
      post 'edit' => 'bids#post_edit', on: :member
      get 'emails', on: :collection
      put 'batch', on: :collection
      get 'reviews', on: :member
      post 'read_notifications', on: :member
    end

    resources :project_revisions, only: [:show] do
      post 'restore', on: :member
    end

    resources :project_attachments, only: [:destroy]

    resources :amendments
    resources :labels, only: [:create, :destroy, :update]
    resources :questions
  end

  resources :response_fields do
    put 'batch', on: :collection
    delete 'response' => 'response_fields#delete_response', on: :member
  end

  resources :comments

  get '404' => 'errors#not_found'

  resources :organizations, path: '', except: [:index, :new, :create] do
    get 'admin', on: :member
    get 'members', on: :member

    resources :teams do
      get 'members', on: :member
      post 'member' => 'teams#add_member', on: :member
      delete 'member' => 'teams#remove_member', on: :member
    end

    resources :form_templates do
      # post 'create_from_existing', on: :collection
      # get 'pick' => 'form_templates#pick_template', on: :collection
      # get 'preview', on: :member
      # post 'use', on: :member
    end

    resources :projects, controller: :organization_projects
    resources :registrations, controller: :organization_registrations
    resources :vendor_registrations, controller: :organization_vendor_registrations do
      post 'approve', on: :member
      post 'reject', on: :member
    end
  end
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  email       :string(255)
#  username    :string(255)
#  logo        :string(255)
#  event_hooks :text
#  created_at  :datetime
#  updated_at  :datetime
#

require_dependency 'enum'

class Organization < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username

  include Behaviors::TargetableForEvents

  has_many :form_templates
  has_many :projects
  has_many :teams, dependent: :destroy
  has_many :organization_team_members, -> { uniq }, through: :teams
  has_many :users, -> { uniq }, through: :organization_team_members
  has_many :registrations, dependent: :destroy
  has_many :vendor_registrations, through: :registrations

  after_create :create_owners_team!

  serialize :event_hooks, Hash

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :email, presence: true, email: true

  validates :username, presence: true, length: { minimum: 3, maximum: 30 },
            format: { with: /\A[a-zA-Z0-9]+\z/, message: "Only letters and numbers allowed" },
            uniqueness: { case_sensitive: false }

  validate :username_is_not_already_a_route

  mount_uploader :logo, LogoUploader

  def self.event_hooks
    @event_hooks ||= Enum.new(
      :twitter, :custom_http
    )
  end

  def self.event_hook_name_for(event_hook)
    {
      :twitter => "Twitter",
      :custom_http => "Custom HTTP"
    }[event_hook.to_sym]
  end

  def run_event_hooks_for_project!(project)
    event_hooks.select { |k, v| v['enabled'] }.each do |k, v|
      case k
      when GlobalConfig.event_hooks[:twitter]
        client = ProcureIoTwitterOAuth.client(token: v['oauth_token'], secret: v['oauth_token_secret'])
        client.update(
          truncate(v['tweet_body'].gsub(':title', project.title)
                                  .gsub(':bids_due_at', project.bids_due_at.to_formatted_s(:readable_dateonly)),
                   length: 140)
        )

      when GlobalConfig.event_hooks[:custom_http]
        HTTParty.post(v['url'],
                      body: ProjectSerializer.new(project, root: false).to_json,
                      headers: { 'Content-Type' => 'application/json' } ) rescue ArgumentError
      end
    end
  end

  def username=(x)
    write_attribute(:username, x.downcase)
  end

  def owners_team
    teams.where("permission_level = ?", Team.permission_levels[:owner]).first
  end

  after_validation :move_friendly_id_error_to_username

  def move_friendly_id_error_to_username
    if (error = errors.messages.delete(:friendly_id))
      errors.messages[:username] = error
    end
  end

  handle_asynchronously :run_event_hooks_for_project!

  private
  def create_owners_team!
    teams.create(name: "Owners", permission_level: Team.permission_levels[:owner])
  end

  def username_is_not_already_a_route
    return if username.blank?
    if (path = Rails.application.routes.recognize_path(username)) &&
       !(path[:controller] == 'organizations' && path[:action] == 'show')
      errors.add(:username, "is reserved")
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # Load
  load_resource

  # Authorize
  before_filter :authorize, except: [:show]
  before_filter only: [:admin] { |c| c.authorize! :collaborate_on, @organization }
  before_filter only: [:edit, :update, :members, :destroy] { |c| c.authorize! :admin, @organization }

  def admin
    current_user.read_notifications(@organization)
    redirect_to organization_projects_path(@organization)
  end

  def show
    @projects = @organization.projects.posted.limit(5)
  end

  def edit
    current_user.read_notifications(@organization)
  end

  def update
    if @organization.update_attributes(organization_params)
      flash[:success] = "Successfully updated organization info."
      redirect_to edit_organization_path(@organization)
    else
      render :edit
    end
  end

  def members
    search_results = User.searcher(params, starting_query: @organization.users)

    respond_to do |format|
      format.html do
        @bootstrap_data = serialized search_results[:results], meta: search_results[:meta]
      end

      format.json do
        render_serialized search_results[:results], meta: search_results[:meta]
      end
    end
  end

  def destroy
    @organization.destroy
    redirect_to root_path
  end

  private
  def organization_params
    params.require(:organization).permit(:name, :email, :username, :logo, :remove_logo)
  end
end

app/views/organizations/_subnav.html.haml
- provide :page_title, @organization.name

%ul.nav.nav-tabs
  %li{"class" => active_page?("organizations#edit") || active_page?("organizations#update")}
    =link_to "Edit Info", edit_organization_path(@organization)
  %li{"class" => active_page?("teams")}=link_to "Teams", organization_teams_path(@organization)
  %li{"class" => active_page?("organizations#members")}=link_to "Member Directory", members_organization_path(@organization)
  %li{"class" => active_page?("organization_registrations")}=link_to "Vendor Registration Forms", organization_registrations_path(@organization)

app/views/organizations/edit.html.haml
- provide :page_action, "Edit info"

= render layout: "shared/user_sidebar" do

  = render "subnav"

  = simple_form_for @organization, validate: true do |f|

    = f.input :name
    = f.input :email
    = f.input :username

    .control-group
      = f.label :logo
      = f.file_field :logo
      %label.checkbox
        = f.check_box :remove_logo
        Remove logo

    - if @organization.logo.url
      %img{"src" => @organization.logo.thumb.url}

    .form-actions
      = f.button :submit, class: 'btn-primary'

  = link_to "Delete Organization", organization_path, method: :delete, data: { confirm: "Are you sure?" }

app/views/organizations/members.html.haml
- provide :page_action, "Member Directory"

= render layout: "shared/user_sidebar" do

  = render "organizations/subnav"

  .alert.alert-info Add and remove members on your <a href="#{organization_teams_path(@organization)}">teams admin</a> page.

  #searchable-table-page.search-page
    :javascript
      new ProcureIo.Backbone.SearchableTable({
        collection: new ProcureIo.Backbone.Collection({
          url: "#{members_organization_path(@organization, format: 'json')}"
        }),
        bootstrapData: #{bootstrap @bootstrap_data.to_json},
        actions: false,
        columns: [
          {
            name: "#{User.human_attribute_name(:name)}",
            accessor: 'display_name',
            sortKey: 'name',
            defaultSort: 'asc'
          },
          {
            name: "#{User.human_attribute_name(:email)}",
            accessor: 'email',
            sortKey: 'email'
          }
        ]
      });

app/views/organizations/new.html.haml
- provide :page_title, "New Organization"
%h3 New Organization

= simple_form_for @organization, validate: true do |f|

  = f.input :name, hint: "The name of your organization, e.g. 'City of Oakland'."
  = f.input :email, hint: 'A public email address for your organization.'
  = f.input :username, hint: "<span class='js-username-wrapper'>Your profile will be at #{request.host}/<span class='js-username'></span></span>"
  = f.input :beta_code, validate: false, hint: "Didn't receive a beta code? Drop us a note at <a href='mailto:hello@dobt.co'>hello@dobt.co</a>."

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    %span.help-inline Or did you want to <a href="#{new_vendor_path}">create a vendor</a>?

app/views/organizations/show.html.haml
- provide :page_title, @organization.name
%h3
  = @organization.name

.row-fluid.organization-profile
  .span3
    - if @organization.logo.url
      %img.logo{"src" => @organization.logo.url}
    %dl
      %dt Email
      %dd= @organization.email

  .span9
    %h4
      Recent Projects
      %small
        %a{"href" => projects_path} See all &rarr;

    .project-list
      - @projects.each do |project|
        = render "projects/project", project: project, show_organization: false